//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jeux.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("jeux.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap avions {
            get {
                object obj = ResourceManager.GetObject("avions", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream bad_answer {
            get {
                return ResourceManager.GetStream("bad_answer", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Correct_answer {
            get {
                return ResourceManager.GetStream("Correct_answer", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Kids_Wallpaper_9 {
            get {
                object obj = ResourceManager.GetObject("Kids-Wallpaper-9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap m9t97_backgrounds_535728798_1920x1080 {
            get {
                object obj = ResourceManager.GetObject("m9t97_backgrounds_535728798_1920x1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap m9t97_backgrounds_535728798_1920x10801 {
            get {
                object obj = ResourceManager.GetObject("m9t97_backgrounds_535728798_1920x10801", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap petit_nuage {
            get {
                object obj = ResourceManager.GetObject("petit_nuage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Quest1 {
            get {
                object obj = ResourceManager.GetObject("Quest1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Quest10 {
            get {
                object obj = ResourceManager.GetObject("Quest10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Quest2 {
            get {
                object obj = ResourceManager.GetObject("Quest2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Quest3 {
            get {
                object obj = ResourceManager.GetObject("Quest3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Quest4 {
            get {
                object obj = ResourceManager.GetObject("Quest4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Quest5 {
            get {
                object obj = ResourceManager.GetObject("Quest5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Quest6 {
            get {
                object obj = ResourceManager.GetObject("Quest6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Quest7 {
            get {
                object obj = ResourceManager.GetObject("Quest7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Quest8 {
            get {
                object obj = ResourceManager.GetObject("Quest8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Quest9 {
            get {
                object obj = ResourceManager.GetObject("Quest9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap si_uew400_fond_bleu_degrade_645dc3 {
            get {
                object obj = ResourceManager.GetObject("si_uew400_fond_bleu_degrade_645dc3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap si_uew400_fond_bleu_degrade_645dc31 {
            get {
                object obj = ResourceManager.GetObject("si_uew400_fond_bleu_degrade_645dc31", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wallpapers_28927_1293523 {
            get {
                object obj = ResourceManager.GetObject("wallpapers_28927_1293523", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wallpapers_28927_12935231 {
            get {
                object obj = ResourceManager.GetObject("wallpapers_28927_12935231", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Wrong_answer {
            get {
                return ResourceManager.GetStream("Wrong_answer", resourceCulture);
            }
        }
    }
}
